#!/bin/bash
#
# This is a script to create an initial 'seed' image based on pristine
# sources.  User images will be built on top of this one.
#
# Two arguments are required:
#
#  * the path to a built server image repository
#  * the name of the seed image to create
#

if [ $# -ne 2 ]; then
	echo "usage: $0 <server-image> <seedname>" >&2
	exit 2
else
	serverimage=$1; shift
	protoname=$1; shift
fi

zoneimagedir="$(dirname $0)"

set -ex

zfs destroy zones/${protoname} || true
zfs create zones/${protoname}

#
# Requisite directories and symlinks
#
for dir in /home /root /var/ssh
do
  mkdir -p /zones/${protoname}/root${dir}
done
mkdir -p -m 1777 /zones/${protoname}/root/tmp
ln -s ./usr/bin /zones/${protoname}/root/bin

#
# Copy in proto directories
#
for dir in etc var
do
  rsync -av ${serverimage}/proto/${dir} /zones/${protoname}/root/
done

#
# Apply manual changes.
#
#  - remove legacy rc2.d scripts
#  - remove /etc/issue
#  - remove SDC-specific root cron
#  - remove legacy /bin/i386 usage from /etc/profile
#  - remove users which may clash with pkgsrc, and sort.
#
rm -f /zones/${protoname}/root/etc/rc2.d/S*
rm -f /zones/${protoname}/root/etc/issue
rm -f /zones/${protoname}/root/etc/cron.d/crontabs/root

ed /zones/${protoname}/root/etc/passwd <<EOF
/^lp/d
/^gdm/d
/^mysql/d
/^openldap/d
/^webservd/d
w
q
EOF

ed /zones/${protoname}/root/etc/shadow <<EOF
/^lp/d
/^gdm/d
/^mysql/d
/^openldap/d
/^webservd/d
w
q
EOF

ed /zones/${protoname}/root/etc/group <<EOF
/^lp/d
/^gdm/d
/^mysql/d
/^openldap/d
/^webservd/d
w
q
EOF

for file in group passwd
do
  sort -t: -k3,3n /zones/${protoname}/root/etc/${file} >/tmp/${file} \
    && mv /tmp/${file} /zones/${protoname}/root/etc/${file}
done

ed /zones/${protoname}/root/etc/user_attr >/dev/null <<EOF
/^lp/d
/^admin/d
w
q
EOF

#
# Generate SVC repository.  Some manifests are missing, apply them manually.
#
${zoneimagedir}/create-smf-repo ${serverimage} ${zoneimagedir}/include/manifests /tmp/repository.db
#svcdir="${serverimage}/projects/illumos/usr/src/cmd/svc"
#for mf in ${serverimage}/proto/lib/svc/manifest/system/boot-archive.xml \
#          ${serverimage}/overlay/generic/lib/svc/manifest/system/sysidtool.xml \
#for mf in ${zoneimagedir}/include/mdata.xml
#do
#  env SVCCFG_REPOSITORY=/tmp/repository.db \
#      SVCCFG_CONFIGD_PATH=${svcdir}/configd/svc.configd-native \
#      ${svcdir}/svccfg/svccfg-native import ${mf}
#done
#
# Import our fake mdata.xml to satisfy SDC 6.5 and 7.0
#
#env SVCCFG_REPOSITORY=/tmp/repository.db \
#    SVCCFG_CONFIGD_PATH=${serverimage}/projects/illumos/usr/src/cmd/svc/configd/svc.configd-native \
#  ${serverimage}/projects/illumos/usr/src/cmd/svc/svccfg/svccfg-native import ${zoneimagedir}/include/mdata.xml
cp /tmp/repository.db /zones/${protoname}/root/etc/svc/repository.db

#
# Apply mode/permission changes based on the published manifest.
#
while read ftype file mode owner group
do
	target="/zones/${protoname}/root/${file}"
	case "${ftype}" in
	d)
		if [ -d ${target} ]; then
			chmod ${mode} ${target}
			chown ${owner}:${group} ${target}
		fi
		;;
	f)
		if [ -f ${target} ]; then
			chmod ${mode} ${target}
			chown ${owner}:${group} ${target}
		fi
		;;
	esac
done < ${serverimage}/manifest.gen

#
# Do just enough zoneinit stuff to get a zone to boot, this will be overwritten
# later when we do a proper smtools install.
#
mkdir -p /zones/${protoname}/root/var/zoneinit
cp ${zoneimagedir}/include/zoneinit.json /zones/${protoname}/root/var/zoneinit
cp ${zoneimagedir}/include/S99final /zones/${protoname}/root/etc/rc2.d/S99final
chmod 0755 /zones/${protoname}/root/etc/rc2.d/S99final
