#!/bin/bash
#
# Creates a seed image from a server-image build.
#
# Requires:
#
#  * path to pre-built server-image repository
#  * name of the seed image to create
#


if [ $# -ne 2 ]; then
	echo "usage: $0 <server-image> <seed-name>" >&2
	exit 2
else
	server_image=$1; shift
	protoname=$1; shift
fi

imagetoolsdir="$(dirname $0)"

set -ex

zfs destroy zones/${protoname} || true
zfs create zones/${protoname}

#
# Requisite directories and symlinks
#
for dir in /home /root /var/ssh
do
  mkdir -p /zones/${protoname}/root${dir}
done
mkdir -p -m 1777 /zones/${protoname}/root/tmp
ln -s ./usr/bin /zones/${protoname}/root/bin

#
# Copy in proto directories
#
for dir in etc var
do
  rsync -av ${server_image}/proto/${dir} /zones/${protoname}/root/
done

#
# Apply manual changes.
#
#  - remove legacy rc2.d scripts
#  - remove /etc/issue
#  - remove SDC-specific root cron
#  - remove legacy /bin/i386 usage from /etc/profile
#  - remove users which may clash with pkgsrc, and sort.
#
rm -f /zones/${protoname}/root/etc/rc2.d/S*
rm -f /zones/${protoname}/root/etc/issue
rm -f /zones/${protoname}/root/etc/cron.d/crontabs/root
ed /zones/${protoname}/root/etc/profile <<EOF
/bin.i386/
s,/bin/i386,[ \`uname -p\` = \"i386\" ],
w
q
EOF
ed /zones/${protoname}/root/etc/passwd <<EOF
/^lp/d
/^gdm/d
/^mysql/d
/^openldap/d
/^webservd/d
w
q
EOF
ed /zones/${protoname}/root/etc/shadow <<EOF
/^lp/d
/^gdm/d
/^mysql/d
/^openldap/d
/^webservd/d
w
q
EOF
ed /zones/${protoname}/root/etc/group <<EOF
/^lp/d
/^gdm/d
/^mysql/d
/^openldap/d
/^webservd/d
w
q
EOF
for file in group passwd
do
  sort -t: -k3,3n /zones/${protoname}/root/etc/${file} >/tmp/${file} \
    && mv /tmp/${file} /zones/${protoname}/root/etc/${file}
done
ed /zones/${protoname}/root/etc/user_attr >/dev/null <<EOF
/^lp/d
/^admin/d
w
q
EOF

#
# Generate SVC repository.  Some manifests are missing, apply them manually.
#
${imagetoolsdir}/create-smf-repo ${server_image} ${imagetoolsdir}/include/manifests /tmp/repository.db
#svcdir="${server_image}/projects/illumos/usr/src/cmd/svc"
#for mf in ${server_image}/proto/lib/svc/manifest/system/boot-archive.xml \
#          ${server_image}/overlay/generic/lib/svc/manifest/system/sysidtool.xml \
#for mf in ${imagetoolsdir}/include/mdata.xml
#do
#  env SVCCFG_REPOSITORY=/tmp/repository.db \
#      SVCCFG_CONFIGD_PATH=${svcdir}/configd/svc.configd-native \
#      ${svcdir}/svccfg/svccfg-native import ${mf}
#done
#
# Import our fake mdata.xml to satisfy SDC 6.5 and 7.0
#
#env SVCCFG_REPOSITORY=/tmp/repository.db \
#    SVCCFG_CONFIGD_PATH=${server_image}/projects/illumos/usr/src/cmd/svc/configd/svc.configd-native \
#  ${server_image}/projects/illumos/usr/src/cmd/svc/svccfg/svccfg-native import ${imagetoolsdir}/include/mdata.xml
cp /tmp/repository.db /zones/${protoname}/root/etc/svc/repository.db

#
# Apply mode/permission changes based on the published manifest.
#
while read ftype file mode owner group
do
	target="/zones/${protoname}/root/${file}"
	case "${ftype}" in
	d)
		if [ -d ${target} ]; then
			chmod ${mode} ${target}
			chown ${owner}:${group} ${target}
		fi
		;;
	f)
		if [ -f ${target} ]; then
			chmod ${mode} ${target}
			chown ${owner}:${group} ${target}
		fi
		;;
	esac
done < ${server_image}/manifest.gen

#
# Do just enough zoneinit stuff to get a zone to boot, this will be overwritten
# later when we do a proper smtools install.
#
mkdir -p /zones/${protoname}/root/var/zoneinit
cp ${imagetoolsdir}/include/zoneinit.json /zones/${protoname}/root/var/zoneinit
cp ${imagetoolsdir}/include/S99final /zones/${protoname}/root/etc/rc2.d/S99final
chmod 0755 /zones/${protoname}/root/etc/rc2.d/S99final
